"""mvp schema

Revision ID: 8bc528198e64
Revises: 
Create Date: 2026-01-07 00:36:17.211159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc528198e64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('trim', sa.String(length=64), nullable=True),
    sa.Column('canonical_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key')
    )
    op.create_index('ix_vehicle_models_year_make_model', 'vehicle_models', ['year', 'make', 'model'], unique=False)
    op.create_table('listing_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_model_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_listing_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'source', 'source_listing_id', name='uq_listing_snapshots_snapshot_source_listingid')
    )
    op.create_index('ix_listing_snapshots_model_date', 'listing_snapshots', ['vehicle_model_id', 'snapshot_date'], unique=False)
    op.create_index('ix_listing_snapshots_snapshot_date', 'listing_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_listing_snapshots_source_listing', 'listing_snapshots', ['source', 'source_listing_id'], unique=False)
    op.create_table('model_weekly_stats',
    sa.Column('vehicle_model_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('median_price', sa.Integer(), nullable=False),
    sa.Column('p10_price', sa.Integer(), nullable=False),
    sa.Column('p90_price', sa.Integer(), nullable=False),
    sa.Column('listing_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vehicle_model_id', 'week_start')
    )
    op.create_index('ix_model_weekly_stats_week_start', 'model_weekly_stats', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_weekly_stats_week_start', table_name='model_weekly_stats')
    op.drop_table('model_weekly_stats')
    op.drop_index('ix_listing_snapshots_source_listing', table_name='listing_snapshots')
    op.drop_index('ix_listing_snapshots_snapshot_date', table_name='listing_snapshots')
    op.drop_index('ix_listing_snapshots_model_date', table_name='listing_snapshots')
    op.drop_table('listing_snapshots')
    op.drop_index('ix_vehicle_models_year_make_model', table_name='vehicle_models')
    op.drop_table('vehicle_models')
    # ### end Alembic commands ###
